# -*- coding: utf-8 -*-
"""Speech_Recognition_Google_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aT0_UbWrSWCb1IrO0w-9fj9P4K3Wmo6
"""

!pip install speechrecognition

import speech_recognition as sp

sp.__version__

recog=sp.Recognizer()

speech=sp.AudioFile('/content/recording.wav')

with speech as noisesource:
  recog.adjust_for_ambient_noise(noisesource)
  audio=recog.record(noisesource)

recog.recognize_google(audio)

recog.recognize_google(audio,show_all=True)