# -*- coding: utf-8 -*-
"""Speech_Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aT0_UbWrSWCb1IrO0w-9fj9P4K3Wmo6
"""

!pip install speechrecognition

import speech_recognition as sp

sp.__version__

recog=sp.Recognizer()

speech=sp.AudioFile('/content/recording.wav')

with speech as filesource:
  audio=recog.record(filesource,offset=6.7)

recog.recognize_google(audio)

with speech as filesource:
  audio1=recog.record(filesource,duration=2)
  audio2=recog.record(filesource,offset=6.7,duration=5)

recog.recognize_google(audio1)

recog.recognize_google(audio2)